### ISSUE TITLE
Plugin commands broken after reloading the plugin

### ISSUE THREAD

**Issue by cupang-afk** [qu4ks/SimplePluginReloader#2]
reload [AFKPlus](https://www.spigotmc.org/resources/afk.35065/) plugin and use `/afk` commands
```
[13:30:31 INFO]: [AFKPlus] Disabling AFKPlus v3.4.1
[13:30:31 INFO]: [AFKPlus] AFKPlus has been disabled!
[13:30:31 INFO]: [AFKPlus] Enabling AFKPlus v3.4.1
[13:30:31 WARN]: Enabled plugin with unregistered ConfiguredPluginClassLoader AFKPlus v3.4.1
[13:30:31 INFO]: [AFKPlus] AFKPlus v.3.4.1 has been enabled!
[13:30:31 INFO]: [AFKPlus] AFKPlus file watcher started!
[13:30:32 INFO]: [AFKPlus] There is no update available
[13:30:34 INFO]: cupang_afk issued server command: /afk
[13:30:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'afk' in net.lapismc.afkplus.commands.AFK(afk)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:925) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/lapismc/afkplus/util/core/placeholder/PlaceholderAPIHook
	at net.lapismc.afkplus.util.core.LapisCoreConfiguration.replacePlaceholders(LapisCoreConfiguration.java:201) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.util.core.LapisCoreConfiguration.getMessage(LapisCoreConfiguration.java:154) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.playerdata.AFKPlusPlayer.getMessage(AFKPlusPlayer.java:399) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.playerdata.AFKPlusPlayer.startAFK(AFKPlusPlayer.java:159) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.commands.AFK.toggleAFK(AFK.java:98) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.commands.AFK.onCommand(AFK.java:51) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.util.core.commands.LapisCoreCommand.onCommand(LapisCoreCommand.java:190) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.util.core.commands.LapisCoreCommand.execute(LapisCoreCommand.java:178) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.lapismc.afkplus.playerdata.AFKPlusPlayer.getMessage(AFKPlusPlayer.java:399) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.playerdata.AFKPlusPlayer.startAFK(AFKPlusPlayer.java:159) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.commands.AFK.toggleAFK(AFK.java:98) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.commands.AFK.onCommand(AFK.java:51) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.util.core.commands.LapisCoreCommand.onCommand(LapisCoreCommand.java:190) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.util.core.commands.LapisCoreCommand.execute(LapisCoreCommand.java:178) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	... 22 more
Caused by: java.lang.ClassNotFoundException: net.lapismc.afkplus.util.core.placeholder.PlaceholderAPIHook
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.lapismc.afkplus.util.core.LapisCoreConfiguration.replacePlaceholders(LapisCoreConfiguration.java:201) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at net.lapismc.afkplus.util.core.LapisCoreConfiguration.getMessage(LapisCoreConfiguration.java:154) ~[AFKPlus-LATEST-[3.4.1].jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 22 more
```

**Comment by egorquaks** [comment]
I just checked the functionality of the commands from AFKPlus after reloading through the SimplePluginReloader on my server and this problem did not occur. I don't know how I can help you.

**Comment by cupang-afk** [comment]
im doing a test again this morning

somehow it solved ?
```
[12:29:59 INFO]: [AFKPlus] Disabling AFKPlus v3.4.1
[12:29:59 INFO]: [AFKPlus] AFKPlus has been disabled!
[12:29:59 INFO]: [AFKPlus] Enabling AFKPlus v3.4.1
[12:29:59 WARN]: Enabled plugin with unregistered ConfiguredPluginClassLoader AFKPlus v3.4.1
[12:30:00 INFO]: [AFKPlus] AFKPlus v.3.4.1 has been enabled!
[12:30:00 INFO]: [AFKPlus] AFKPlus file watcher started!
[12:30:00 INFO]: [AFKPlus] There is no update available
[12:30:02 INFO]: cupang_afk issued server command: /afk
[12:30:02 INFO]: ▶ cupang_afk now is AFK
```

last time i tested, it broke 3 plugin after reload AFKPlus, GSit, and a pluginmanager 

im gonna close this issue, sorry for the inconvenience
